version: "3.8"

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    environment: 
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DATABASE: postgres
      KC_STORAGE: jpa
      KC_DB_URL: jdbc:postgresql://pg/keycloak  # Alterado para referenciar o serviço PostgreSQL
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_DEBUG: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    command: start --optimized
    ports:
      - 8080:8080
    networks:
      - default
    volumes:
      - keycloak-data:/opt/jboss/keycloak/data  # Corrigido o caminho do volume
    depends_on:
      - pg

  pg:
    image: postgres:16.0
    container_name: pg
    environment: 
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    networks: 
      - default
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  pgdata:
    driver: local
  keycloak-data: 
    driver: local
