version: '3.1'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mongo:6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=tweets
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "27017:27017"

  mongo-express:
      image: mongo-express
      restart: always
      environment:
        ME_CONFIG_MONGODB_SERVER: db
        ME_CONFIG_MONGODB_AUTH_USERNAME: root
        ME_CONFIG_MONGODB_AUTH_PASSWORD: root
      depends_on:
        - db
      ports:
        - "8081:8081"